include common.mk

CC = arm-linux-gcc
CXX = arm-linux-g++
LEVELS = lev1 lev2 lev3 lev4 lev5 lev6 lev7 lev8 lev9 lev10 lev11 lev12 lev13 lev14 lev15 lev16 lev17

PLATFORM_CFLAGS = -DHIGH_NoKeyboard

zip: $(TARGET) platform/miyoo/mslug.cfg icon.png _README_final.txt _LISEZMOI_final.txt
	-rm minislug.zip
	zip -j minislug.zip $(TARGET) platform/miyoo/mslug.cfg icon.png _README_final.txt _LISEZMOI_final.txt
	zip -r minislug.zip $(LEVELS) gfx sfx
.PHONY: zip
