include common.mk

CC = mipsel-linux-gcc
CXX = mipsel-linux-g++
LEVELS = lev1 lev2 lev3 lev4 lev5 lev6 lev7 lev8 lev9 lev10 lev11 lev12 lev13 lev14 lev15 lev16 lev17

PLATFORM_CFLAGS = -DHIGH_NoKeyboard -DNO_FRAME_SKIPPING -DUSE_HOMEDIR

opk: $(TARGET) platform/retrofw/mslug.cfg icon.png _README_final.txt _LISEZMOI_final.txt platform/retrofw/minislug.retrofw.desktop
	mksquashfs $^ $(LEVELS) gfx sfx minislug.opk -noappend -no-xattrs
.PHONY: opk
